### ISSUE TITLE
minio 操作的时候报错，aws cli可以正常操作。

### ISSUE THREAD

**Issue by zhoushoujianwork** [patsnapops/cloud-bucket-sync#8]
```bash
[root@zhoushoujianworkspace cloud-bucket-sync]# cbs b ls s3://local-llm/ -p mino
panic: profile mino not found,please check cli.yaml config

goroutine 1 [running]:
cbs/cmd.glob..func3(0x288bea0?, {0xc00054e8a0, 0x1, 0x3?})
        /data/github/cloud-bucket-sync/cmd/bucket.go:177 +0x9e5
github.com/spf13/cobra.(*Command).execute(0x288bea0, {0xc00054e840, 0x3, 0x3})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x2889940)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
cbs/cmd.Execute(...)
        /data/github/cloud-bucket-sync/cmd/root.go:49
main.main()
        /data/github/cloud-bucket-sync/main.go:19 +0x5a

# aws s3 ls 正常
[root@zhoushoujianworkspace cloud-bucket-sync]# aws s3 ls --profile=minio --endpoint=http://xxx.patsnap.io/ s3://local-llm/raw/
                           PRE book/
                           PRE common/
                           PRE csco/
```
debug发现 aws cli支持域名格式如上，cbs使用的是桶名放在二级域名的规则。可能需要适配。
```
023-09-05 14:12:17,264 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): local-minio-s3-api.patsnap.io:80
2023-09-05 14:12:17,432 - MainThread - urllib3.connectionpool - DEBUG - http://local-minio-s3-api.patsnap.io:80 "GET /local-llm?list-type=2&prefix=raw%2F&delimiter=%2F&encoding-type=url HTTP/1.1" 200 1496
```

**Comment by zhoushoujianwork** [comment]
具体看下 https://docs.aws.amazon.com/zh_cn/AmazonS3/latest/userguide/access-bucket-intro.html

**Comment by zhoushoujianwork** [comment]
Virtual hosted style is supported when you enable MINIO_DOMAIN env.
https://github.com/minio/minio/issues/10910
